/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps\delegated-source-gatekeeper\wrangler.jsonc --include-runtime=false --env-interface=GeneratedEnv apps\delegated-source-gatekeeper\src\worker-configuration.d.ts` (hash: 79e371be3ffba960c2b17818a644bdc2)
interface __BaseEnv_GeneratedEnv {
	SOURCE_DB: D1Database;
	ENVIRONMENT: "development";
	DEPLOYMENT_ID: "deployment:default";
	GOOGLE_CLIENT_ID: "configure-me";
	GITHUB_CLIENT_ID: "configure-me";
	CREDENTIAL_KEY_ID: "kek:development";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "DEPLOYMENT_ID" | "GOOGLE_CLIENT_ID" | "GITHUB_CLIENT_ID" | "CREDENTIAL_KEY_ID">> {}
}
