/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps\discord-adapter\wrangler.jsonc --include-runtime=false --env-interface=GeneratedEnv apps\discord-adapter\src\worker-configuration.d.ts` (hash: 04c0993d8aa767d5a3682518c820cf00)
interface __BaseEnv_GeneratedEnv {
	ENVIRONMENT: "development";
	DEPLOYMENT_ID: "deployment:default";
	DISCORD_APPLICATION_ID: "1537317765558304838";
	DISCORD_PUBLIC_KEY: "776cd97855a80999f08692fb0b2f7bdb52f54a170823e681e88530baa815e70f";
	DISCORD_DEDUPE: DurableObjectNamespace<import("./index").DiscordDedupe>;
	ASSISTANT: Service /* entrypoint DiscordEntrypoint from opap-assistant */;
	DISCORD_GATEKEEPER: Fetcher /* opap-discord-gatekeeper */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "DiscordDedupe";
	}
	interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "DEPLOYMENT_ID" | "DISCORD_APPLICATION_ID" | "DISCORD_PUBLIC_KEY">> {}
}
