/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps\delegated-agent-api\wrangler.jsonc --include-runtime=false --env-interface=GeneratedEnv apps\delegated-agent-api\src\worker-configuration.d.ts` (hash: cbb9797e09a8c6936e730c2c105b7c37)
interface __BaseEnv_GeneratedEnv {
	AI: Ai;
	ENVIRONMENT: "development";
	DEPLOYMENT_ID: "deployment:default";
	DELEGATED_ISSUER: "https://issuer.example.invalid";
	DELEGATED_AUDIENCE: "configure-me";
	DELEGATED_JWKS_URI: "https://issuer.example.invalid/.well-known/jwks.json";
	AI_GATEWAY_ID: "default";
	WORKERS_AI_MODEL: "@cf/google/gemma-4-26b-a4b-it";
	AI_MONTHLY_OVERAGE_USD: "5";
	DELEGATED_QUOTA: DurableObjectNamespace /* QuotaDurableObject from opap-quota */;
	CONTROL: Fetcher /* opap-policy-control */;
	DELEGATED_SOURCE_READ: Service /* entrypoint DelegatedSourceReadEntrypoint from opap-delegated-source-gatekeeper */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "DEPLOYMENT_ID" | "DELEGATED_ISSUER" | "DELEGATED_AUDIENCE" | "DELEGATED_JWKS_URI" | "AI_GATEWAY_ID" | "WORKERS_AI_MODEL" | "AI_MONTHLY_OVERAGE_USD">> {}
}
