/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps\maintenance-worker\wrangler.jsonc --include-runtime=false --env-interface=GeneratedEnv apps\maintenance-worker\src\worker-configuration.d.ts` (hash: c180b68b88ab9eeba1162f1e386da222)
interface __BaseEnv_GeneratedEnv {
	PRIVATE_R2: R2Bucket;
	CONTROL_DB: D1Database;
	CONVERSATIONS: DurableObjectNamespace /* ConversationAgent from opap-conversation-agent */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
