/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps\google-gatekeeper\wrangler.jsonc --include-runtime=false --env-interface=GeneratedEnv apps\google-gatekeeper\src\worker-configuration.d.ts` (hash: 232e5c8d71b11064c8a229450d68e8ab)
interface __BaseEnv_GeneratedEnv {
	GATEKEEPER_DB: D1Database;
	ENVIRONMENT: "development";
	CREDENTIAL_KEY_ID: "kek:development";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "CREDENTIAL_KEY_ID">> {}
}
