/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps\policy-control-worker\wrangler.jsonc --include-runtime=false --env-interface=GeneratedEnv apps\policy-control-worker\src\worker-configuration.d.ts` (hash: ef808a7ff690894d01e2f36cf77ed7e4)
interface __BaseEnv_GeneratedEnv {
	CONTROL_DB: D1Database;
	ENVIRONMENT: "development";
	AUDIT_LEDGER: DurableObjectNamespace /* AuditLedger from opap-audit-ledger */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT">> {}
}
