/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps\discord-gatekeeper\wrangler.jsonc --include-runtime=false --env-interface=GeneratedEnv apps\discord-gatekeeper\src\worker-configuration.d.ts` (hash: 85c2e42e2c5d7cc36c763838fbf99afc)
interface __BaseEnv_GeneratedEnv {
	DISCORD_DB: D1Database;
	ENVIRONMENT: "development";
	DEPLOYMENT_ID: "deployment:default";
	DISCORD_APPLICATION_ID: "1537317765558304838";
	EXECUTION_LEASE_PUBLIC_JWK: "{}";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "DEPLOYMENT_ID" | "DISCORD_APPLICATION_ID" | "EXECUTION_LEASE_PUBLIC_JWK">> {}
}
