/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps\public-agent-api\wrangler.jsonc --include-runtime=false --env-interface=GeneratedEnv apps\public-agent-api\src\worker-configuration.d.ts` (hash: c2de2fff3ea666590701330cb71ced68)
interface __BaseEnv_GeneratedEnv {
	PUBLIC_RATE_LIMITER: RateLimit;
	AI_SEARCH: AiSearchInstance;
	AI: Ai;
	ENVIRONMENT: "development";
	DEPLOYMENT_ID: "deployment:default";
	PUBLIC_SOURCES_JSON: "[{\"sourceId\":\"source:public-fixture\",\"kind\":\"fixture\",\"revision\":\"1\",\"cacheTtlSeconds\":300},{\"sourceId\":\"source:public-ai-search\",\"kind\":\"ai-search\",\"transport\":\"workers-binding\",\"revision\":\"okidev-web-2026-08-vector-v3\",\"cacheTtlSeconds\":300,\"title\":\"OkiDev public documentation\",\"retrievalPolicy\":{\"retrievalType\":\"vector\",\"candidateResults\":10,\"matchThreshold\":0.4,\"contextExpansion\":1,\"answerContextCharacters\":4000,\"answerMaxOutputTokens\":4096,\"answerReasoningEffort\":\"low\"}},{\"sourceId\":\"source:public-ai-search-rules\",\"kind\":\"ai-search\",\"transport\":\"workers-binding\",\"revision\":\"okidev-web-rules-2026-08-vector-v3\",\"cacheTtlSeconds\":300,\"title\":\"OkiDev public rules\",\"retrievalPolicy\":{\"retrievalType\":\"vector\",\"candidateResults\":10,\"matchThreshold\":0.3,\"contextExpansion\":1,\"answerContextCharacters\":4000,\"answerMaxOutputTokens\":4096,\"answerReasoningEffort\":\"low\"}}]";
	PRICING_CATALOG_VERIFIED_AT: "2026-08-07T00:00:00.000Z";
	AI_MONTHLY_OVERAGE_USD: "5";
	AI_GATEWAY_ID: "default";
	WORKERS_AI_MODEL: "@cf/google/gemma-4-26b-a4b-it";
	PUBLIC_QUOTA: DurableObjectNamespace /* QuotaDurableObject from opap-quota */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "DEPLOYMENT_ID" | "PUBLIC_SOURCES_JSON" | "PRICING_CATALOG_VERIFIED_AT" | "AI_MONTHLY_OVERAGE_USD" | "AI_GATEWAY_ID" | "WORKERS_AI_MODEL">> {}
}
