/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps\quota-worker\wrangler.jsonc --include-runtime=false --env-interface=GeneratedEnv apps\quota-worker\src\worker-configuration.d.ts` (hash: cad33dfdc47321da891582f206c7e56f)
interface __BaseEnv_GeneratedEnv {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "QuotaDurableObject";
	}
	interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
