/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps\conversation-agent\wrangler.jsonc --include-runtime=false --env-interface=GeneratedEnv apps\conversation-agent\src\worker-configuration.d.ts` (hash: a7f3403d3e91773e784375a27a1dfe00)
interface __BaseEnv_GeneratedEnv {
	TASK_RUNNER: Service /* entrypoint ScheduledTaskEntrypoint from opap-assistant */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "ConversationAgent";
	}
	interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
