/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps\audit-ledger-worker\wrangler.jsonc --include-runtime=false --env-interface=GeneratedEnv apps\audit-ledger-worker\src\worker-configuration.d.ts` (hash: 7f9fbd586ac5a5c44f192027fc83f209)
interface __BaseEnv_GeneratedEnv {
	AUDIT_CHECKPOINTS: R2Bucket;
	CONTROL_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "AuditLedger";
	}
	interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
