/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps\assistant-worker\wrangler.jsonc --include-runtime=false --env-interface=GeneratedEnv apps\assistant-worker\src\worker-configuration.d.ts` (hash: 254ccab355dbeb4c9c0119fd4066e1db)
interface __BaseEnv_GeneratedEnv {
	AI: Ai;
	ENVIRONMENT: "development";
	DEPLOYMENT_ID: "deployment:default";
	OWNER_EMAIL: "owner@example.invalid";
	OWNER_TIME_ZONE: "Asia/Tokyo";
	ACCESS_ISSUER: "https://example.cloudflareaccess.com";
	ACCESS_AUDIENCE: "configure-me";
	ACCESS_JWKS_URI: "https://example.cloudflareaccess.com/cdn-cgi/access/certs";
	WORKERS_AI_MODEL: "@cf/google/gemma-4-26b-a4b-it";
	AI_GATEWAY_ID: "default";
	DISCORD_APPLICATION_ID: "1537317765558304838";
	CONVERSATIONS: DurableObjectNamespace /* ConversationAgent from opap-conversation-agent */;
	OWNER_QUOTA: DurableObjectNamespace /* QuotaDurableObject from opap-quota */;
	CONTROL: Fetcher /* opap-policy-control */;
	GOOGLE_GATEKEEPER: Fetcher /* opap-google-gatekeeper */;
	GITHUB_GATEKEEPER: Fetcher /* opap-github-gatekeeper */;
	DISCORD_GATEKEEPER: Fetcher /* opap-discord-gatekeeper */;
	DELEGATED_SOURCE_ADMIN: Service /* entrypoint DelegatedSourceAdminEntrypoint from opap-delegated-source-gatekeeper */;
	MAINTENANCE: Fetcher /* opap-maintenance */;
	PLUGIN_RUNTIME: Fetcher /* opap-plugin-runtime */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "DEPLOYMENT_ID" | "OWNER_EMAIL" | "OWNER_TIME_ZONE" | "ACCESS_ISSUER" | "ACCESS_AUDIENCE" | "ACCESS_JWKS_URI" | "WORKERS_AI_MODEL" | "AI_GATEWAY_ID" | "DISCORD_APPLICATION_ID">> {}
}
