/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps\plugin-runtime-worker\wrangler.jsonc --include-runtime=false --env-interface=GeneratedEnv apps\plugin-runtime-worker\src\worker-configuration.d.ts` (hash: 9421814812c320800dc727eac8d4ba71)
interface __BaseEnv_GeneratedEnv {
	PRIVATE_R2: R2Bucket;
	PLUGIN_RUNTIME_PROTOCOL_VERSION: "1";
	DEPLOYMENT_ID: "deployment:default";
	SANDBOX: DurableObjectNamespace<import("./index").Sandbox>;
	PLUGIN_COORDINATOR: DurableObjectNamespace<import("./index").PluginCoordinator>;
	QUOTA: DurableObjectNamespace /* QuotaDurableObject from opap-quota */;
	CONTROL: Fetcher /* opap-policy-control */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "PluginCoordinator" | "Sandbox";
	}
	interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PLUGIN_RUNTIME_PROTOCOL_VERSION" | "DEPLOYMENT_ID">> {}
}
