/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps\github-gatekeeper\wrangler.jsonc --include-runtime=false --env-interface=GeneratedEnv apps\github-gatekeeper\src\worker-configuration.d.ts` (hash: afaef9068820b4e2af2f223b704d201b)
interface __BaseEnv_GeneratedEnv {
	GATEKEEPER_DB: D1Database;
	ENVIRONMENT: "development";
	GITHUB_CLIENT_ID: "configure-me";
	CREDENTIAL_KEY_ID: "kek:development";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "GITHUB_CLIENT_ID" | "CREDENTIAL_KEY_ID">> {}
}
